apiVersion: v1
kind: Service
metadata:
  name: tomcat-middleware-svc
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: tomcat-middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-middleware
  namespace: production
  labels:
    app: tomcat-middleware
    tier: middleware
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25
  selector:
    matchLabels:
      app: tomcat-middleware
  template:
    metadata:
      labels:
        app: tomcat-middleware
    spec:
      containers:
        - name: middleware-engine
          image: mathade/core-aegis-tomcat:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
