apiVersion: v1
kind: Service
metadata:
  name: aegisops-insights-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: aegisops-insights
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegisops-insights-deployment
  namespace: default
  labels:
    app: aegisops-insights
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: aegisops-insights
  template:
    metadata:
      labels:
        app: aegisops-insights
    spec:
      containers:
        - name: telemetry-ui-engine
          image: mathade/core-aegis-tomcat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /index.jsp
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.jsp
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
